version: '3.2'

services:
  valiator:
    image: metronome-validator:latest
    volumes:
      - type: bind
        source: ./validator.env
        target: /usr/src/metronome-validator/validator.env
      # - .:/usr/src/metronome-validator
    network_mode: host
    depends_on: 
      - redis-server
    restart: always
  redis-server:
    container_name: redis-server
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    restart: always