version: '3.2'

services:
  validator0.3.3:
    container_name: validator0.3.3
    image: metronome-validator:0.3.3
    volumes:
      - /usr/src/metronome-validator/node_modules
      - .:/usr/src/metronome-validator
    network_mode: "service:redis"
    environment:
      - etc_http_url=${etc_http_url}
      - qtum_http_url=${qtum_http_url}
      - qtum_validator_address=${qtum_validator_address}
      - qtum_network=${qtum_network}
      - etc_validator_address=${etc_validator_address}
      - etc_validator_password=${etc_validator_password}
      - eth_keystore_filename=${eth_keystore_filename}
      - etc_keystore_filename=${etc_keystore_filename}
      - etc_ws_url=${etc_ws_url}
      - eth_http_url=${eth_http_url}
      - eth_validator_address=${eth_validator_address}
      - eth_validator_password=${eth_validator_password}
      - eth_ws_url=${eth_ws_url}
      - REDIS_URL=redis://127.0.0.1:6379/5
      - walletMnemonic=${walletMnemonic}
      - uselocalkeystore=${uselocalkeystore}
    depends_on: 
      - redis
    restart: always
  redis:
    image: redis:5.0.3
    container_name: redis
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    network_mode: host
    volumes:
      - ${REDIS_DATA}:/data
    restart: always