version: '3.2'

services:
  valiator:
    image: metronome-validator:latest
    # volumes:
    #   - .:/usr/src/metronome-validator
    network_mode: host
    environment:
      - etc_http_url=${eth_http_url}
      - etc_validator_address=${etc_validator_address}
      - etc_validator_password=${etc_validator_password}
      - etc_ws_url=${etc_ws_url}
      - eth_http_url=${eth_http_url}
      - eth_validator_address=${eth_validator_address}
      - eth_validator_password=${eth_validator_password}
      - eth_ws_url=${eth_ws_url}
      - REDIS_URL=redis://127.0.0.1:6379/3
    depends_on: 
      - redis
    restart: always
  redis:
    image: redis:5.0.3
    container_name: redis
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    restart: always